### ISSUE TITLE
A Roughly Implementation of SRL-Python

### ISSUE THREAD

**Issue by soasme** [SimpleRegex/SRL-Python#1]
Hey, Guys.

I did not notice the discussion on https://github.com/SimpleRegex/SRL-PHP/issues/22 and has working on a roughly implementation of [SRL-Python](https://github.com/soasme/srl.py)

Hoping to avoid the conflict of development of this library and to merge some of the implementation into this repo.

Current State:
- Builder is done
- Passed All the Features described in https://simple-regex.com/documentation
- PYPI Package name has registered: https://pypi.python.org/pypi/SRL

TODO:
- Write DSL parser
- Applying Rules described in https://github.com/SimpleRegex/Test-Rules

**Comment by soasme** [comment]
@mhbashari @KarimGeiger I would appreciate it if you guys review this issue :)

**Comment by KarimGeiger** [comment]
Hi @soasme,

thanks for your great work, looks pretty decent. As far as I know are you the first one to contribute, so I'd say first come, first serve.

I'll give you access to this repository, and if you like, you can join our developer Slack team as well.

**Comment by soasme** [comment]
I am willing to maintain this repository :)
It's my honor!

**Comment by soasme** [comment]
I will clean up the code and merge the first version code into this repo a few hours later :shipit:
